```yaml
---
- name: Setup Fedora Workstation
  hosts: localhost
  become: yes
  tasks:
    - name: Update package manager cache
      dnf:
        update_cache: yes

    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - @kde-desktop
        - kde-connect
        - kde-telepathy
        - kde-partitionmanager
        - dolphin
        - kate
        - ark
        - gparted
        - chromium
        - gstreamer1-plugins-good
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-bad-free-extras
        - gstreamer1-plugins-ugly
        - gstreamer1-plugins-bad-free-gtk
        - gstreamer1-plugins-bad-free-fluidsynth
        - gstreamer1-libav
        - ffmpeg
        - xine-lib-extras-freeworld
        - akmod-nvidia
        - kernel-modules-extra
        - steam
        - discord
        - obs-studio
        - code
        - nano
        - git
        - fuse-exfat
        - exfat-utils
        - vlc

    - name: Create swap file
      command: fallocate -l 32G /swapfile
      args:
        creates: /swapfile

    - name: Set swap file permissions
      command: chmod 600 /swapfile

    - name: Make swap file
      command: mkswap /swapfile

    - name: Enable swap file
      command: swapon /swapfile

    - name: Add swap file to fstab
      lineinfile:
        path: /etc/fstab
        line: '/swapfile   none    swap    sw    0   0'

    - name: Enable non-free repositories
      dnf:
        name: rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm,rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
        state: present
      args:
        creates: /etc/yum.repos.d/rpmfusion-free.repo

    - name: Install NVIDIA drivers
      dnf:
        name: akmod-nvidia
        state: present

    - name: Rebuild initramfs
      command: dracut --force

    - name: Reboot to apply changes
      command: shutdown -r now
      async: 0
      poll: 0
```
